#!/bin/bash

# To make git run unit tests and lint tests, softlink this file into the
# .git/hooks directory.  The following command will get that done:
#   ln -s ../../prepare-commit-msg .git/hooks/prepare-commit-msg

(
    echo 'Test coverage is as follows:'
    COVERAGE=coverage
    if [ z`which coverage` = z ]
    then
        COVERAGE=python-coverage
    fi
    $COVERAGE report -m
    echo
    echo 'The Python linter found the following issues:'
    pylint --rcfile=pylintrc --reports=n *.py
    echo
    echo 'The Python formatters recommend the following changes:'
    unify *.py
    autoflake *.py
    autopep8 --max-line-length 80 -d *.py
    docformatter --no-blank --wrap-summaries 80 --wrap-descriptions 80 *.py
) | sed -e 's/^/# /' >> $1
